version: '3.9'
services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: todo-db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - todo-db-data:/var/lib/postgresql/data

volumes:
  todo-db-data: